name: claudeai-desktop
base: core22
version: '1.0.0'
summary: Claude Desktop App
icon: assets/icon.png
description: |
  Claude Desktop is a lightweight Electron-based desktop app providing a smooth and fast experience with Claude AI.

grade: stable
confinement: classic

title: Claude Desktop
contact: prevailexcellent@gmail.com
license: MIT
website: https://github.com/prevailexcel/claude-desktop-client
source-code: https://github.com/prevailexcel/claude-desktop-client
issues: https://github.com/prevailexcel/claude-desktop-client/issues
donation: https://buymeacoffee.com/prevail

apps:
  claude-desktop:
    command: opt/claude-desktop/claude-desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - browser-support
      - home

parts:
  claude-desktop:
    plugin: dump
    source: dist/linux-unpacked
    organize:
      '*': opt/claude-desktop/
    stage-packages:
      - libnss3
      - libgbm1
      - libdrm2
